"""Routing labels and dataset loading.

- data/train.jsonl: generated by a local open-weight model (scripts/generate_train.py)
- data/test.jsonl: held out, written separately (never generated by a model under test)
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

ROUTES = ["drug_label", "clinical_trials", "coverage", "human_review", "out_of_scope"]

ROUTE_DEFINITIONS = {
    "drug_label": "Asks what an FDA drug label says (indications, boxed warning, warnings, contraindications, adverse reactions, dosing, specific populations).",
    "clinical_trials": "Asks about clinical trials (which exist, phases, status, sponsors, endpoints, enrollment, sites).",
    "coverage": "Asks about insurance coverage, reimbursement, billing codes, prior authorization, Medicare coverage determinations, or patient access programs.",
    "human_review": "Must go to a human compliance reviewer: promotional or marketing copy, superiority claims, off-label promotion, advice for a specific patient, or content with patient identifiers.",
    "out_of_scope": "Unrelated to drug evidence (IT, HR, facilities, scheduling, general coding, small talk).",
}


def load(split: str) -> tuple[list[str], list[int]]:
    rows = [json.loads(l) for l in (ROOT / "data" / f"{split}.jsonl").read_text().splitlines() if l.strip()]
    return [r["text"] for r in rows], [ROUTES.index(r["label"]) for r in rows]
